import {
  IMAGES_FOLDER_PATH,
  CONTACT_EMAIL,
  SERVICES_GATEWAY_URL
} from "./config";

import { SERVICES_API_KEY } from "./secrets";

export {
  IMAGES_FOLDER_PATH,
  CONTACT_EMAIL,
  SERVICES_GATEWAY_URL,
  SERVICES_API_KEY
};
